version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    parameters:
      registery:
        type: string  
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build and deploy docker image'
          command: |
            docker build --cache-from=app -t app .
            docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            docker tag app << parameters.registery >>:${CIRCLE_SHA1}
            docker push << parameters.registery >>:${CIRCLE_SHA1}
  publish-dev:
    docker:
      - image: tribeplatform/cli:1.0.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    environment:
      DOCKER_REGISTERY: tribeplatform/google-analytics
    steps:
      - checkout
      - run:
          name: 'Deploy app on DEV environment'
          command: |
            ops init -i -e ermia@bettermode.com -u $OPS_USERNAME -p $OPS_PASSWORD
            ops app create -n google-analytics -i $DOCKER_REGISTERY:$CIRCLE_SHA1
            ops service deploy -s google-analytics -i $DOCKER_REGISTERY:$CIRCLE_SHA1
  publish-prod:
    docker:
      - image: tribeplatform/cli:1.0.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    environment:
      DOCKER_REGISTERY: tribeplatform/google-analytics
    steps:
      - checkout
      - run:
          name: 'Deploy app on PRD environment'
          command: |
            ops init -i -e ermia@bettermode.com -u $OPS_USERNAME -p $OPS_PASSWORD
            ops app create -n google-analytics -i $DOCKER_REGISTERY:$CIRCLE_SHA1 -e prd
            ops service deploy -s google-analytics -e prd -i $DOCKER_REGISTERY:$CIRCLE_SHA1
workflows:
  app:
    jobs:
      - build:
          registery: tribeplatform/google-analytics
          context: App
          filters:
            branches:
              only:
                - master
                - dev
      - publish-dev:
          context: App
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish-prod:
          context: App
          requires:
            - hold
          filters:
            branches:
              only:
                - master
